version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db 
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=postgres;User Id=postgres;Password=password;
      - Hashids__Salt=himalaya
      - Hashids__Alphabet=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
